# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.2"

      - name: Install staticcheck
        run: go get honnef.co/go/tools/cmd/staticcheck
      - name: Install golangci-lint
        run: go get github.com/golangci/golangci-lint/cmd/golangci-lint
      - name: Install gocritic
        run: go get github.com/go-critic/go-critic/cmd/gocritic
      - name: Install gci
        run: go get github.com/daixiang0/gci
      - name: Install goimports
        run: go get golang.org/x/tools/cmd/goimports
      - name: Install errcheck
        run: go get github.com/kisielk/errcheck
      - name: Install vet
        run: go get github.com/bazelbuild/rules_go@v0.53.0

      - name: Install dependencies
        run: go mod download

      - name: Add Go tools to PATH
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

  # analyze:
  #   runs-on: ubuntu-latest
  #   needs: install
  #   env:
  #     GOFLAGS: -buildvcs=false
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-go@v4
  #       with:
  #         go-version: "1.24.2"

  #     # - name: Analyze
  #     #   run: |
  #     #     make analyze
  #     - name: GolangCI-Lint
  #       run: |
  #         make lint
  build:
    runs-on: ubuntu-latest
    needs: install
    # needs: analyze
    env:
      GOFLAGS: -buildvcs=false
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.2"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
